### ISSUE TITLE
The "key" line you deleted in the manifest JSON breaks everything

### ISSUE THREAD

**Issue by mrkevinlin** [joaomgcd/JoinChrome#1]
Prompts infinite Google account sign-ins.

Returning the "key: " line fixes it.

**Comment by joaomgcd** [comment]
Thanks. I thought it was specific to my PC so I removed it. I'll put it pack on the next commit

**Comment by mrkevinlin** [comment]
Well, interestingly, it looks like we need it during development, but if you try to upload the extension to the Web Store with the key value in the manifest, it will reject it because the key is actually generated specific to the Web Store listing. But if the key is the same then it should be no problem. I think that's what these people were saying:
https://github.com/yeoman/generator-chrome-extension/issues/59

**Comment by joaomgcd** [comment]
Yep :) Thank for letting me know!
