### ISSUE TITLE
Notifications not being shown correctly when using the Windows 10 screensaver (+login screen) setting

### ISSUE THREAD

**Issue by ars4l4n** [joaomgcd/JoinChrome#100]
Hi, I'm using Join to receive persistent smartphone calendar notifications that have to be clicked away instead of disappearing after a few minutes which is an unconvenient thing Windows Calendar would do.

So far I'm happy. The following thing doesn't work though:

Let's say I use a [screensaver with the "login page at reactivation"-setting activated](https://i.imgur.com/X4B7Q6o.png) on Windows 10 and get 3 notifications while I was afk: only the first will be shown on the login screen and after logging back in the others will still not appear (which they would if you used no screensaver+login page at reactivation)

I tried to look for some workarounds:

~~-screensaver without login page at reactivation ->no visual notifications (you can hear their sound though)~~

~~-completely signing off from my current usersession ->no notifications at all~~

~~-sleep mode -> no notifications at all~~

\-Using the "Turning off the display after x minutes" setting -> worked, but I avoided this setting for several reasons:

For one thing, I run stuff in the background that interferes with it. I'd need to make more complicated adjustments to that. But more importantly, this setting makes my BenQ GW2470 monitor show a blue full brightness notification on the screen (which I could btw only avoid by using the setting "hdmi auto switch" and disconnect my second device, the raspberry pi from the monitor so that I don't have to manually switch back to my main monitor each time the display turns off via the windows setting. Now I only get a black screen with a smaller white full brightness "no input found", better but not optimal)

You couldn't even solve the issue by turning off the monitor via a smart ac plug because when turning it on afterwards, you get a full brightness blue screen with an ironic "BenQ eye care" logo as well

What I need to do now is look out for another monitor that doesn't have this issue. Let's see if I can find one.

A lot of people may face a part of this issue to some degree so it could be a good idea if you tried to find a fix for the login screen/screen saver notifications.

**Comment by joaomgcd** [comment]
Unfortunately since this is using Chrome notifications (which are redirected to the Windows Notification Center) I have no control over how this works sorry. :/ Wish I could help somehow but I don't think I can. Maybe Chrome devs can do something about it?

**Comment by joaomgcd** [comment]
Unfortunately I wasn't able to do that yet... Will have to figure out a way to do it maybe without using Windows notification center which seems too limited. Thanks!

**Comment by ars4l4n** [comment]
thank you too
I'll keep an eye out for your updates
