### ISSUE TITLE
Can't click on anything on Chromium

### ISSUE THREAD

**Issue by belidzs** [joaomgcd/JoinChrome#101]
I'm using Version 64.0.3282.119 (Official Build) (64-bit) of Chromium on Windows 10. Join version is  1.8.23

I've uninstalled a previous version of Chromium to try the beta Firefox extension (Chromium was only installed to use join) but it didn't work well so I've reinstalled Chromium.

After the clean installation I've downloaded the extension from the Chrome store, logged in to my Google account, but now
* the dropdown menu is empty (I can still see the headers and click on them)
* the options page loads, but none of the items are clickable
* console shows the error messages below

## options.html
```
options.js:2 Uncaught TypeError: chrome.extension.getBackgroundPage(...).setLocalDeviceNameFromDeviceList is not a function
    at options.js:2
```

## join.html
```
gcm.js:1213 Uncaught SyntaxError: Unexpected token {
join.js:1029 Uncaught ReferenceError: updateBadgeText is not defined
    at join.js:1029
```

I have deleted all Chromium-related data files from my Windows profiled, then reinstalled Chromium again, without success.

**Comment by joaomgcd** [comment]
Hi. Seems like that version of Chromium is rather old? Can you please try with the the latest version?

**Comment by belidzs** [comment]
You're right, I've upgraded to latest (I've used chromium-stable on chocolatey and for some reason it's stuck at v64), and all these issues went away

Thanks!

**Comment by joaomgcd** [comment]
cool! 👍
