### ISSUE TITLE
Is there any way to make the extension work on the latest Edge browser(based on chromium)

### ISSUE THREAD

**Issue by ouldsmobile** [joaomgcd/JoinChrome#102]
It lets me choose the user account but then doesn't seem to ask for the device name etc. In settings it just says "undefined" under this device. I did import from Chrome so maybe that caused an issue but I did also try removing the extension and re-adding with the same behaviour.

**Comment by joaomgcd** [comment]
Hi. The extension is not going to work but the desktop and new web app will 👍 
Check here: https://www.reddit.com/r/JoinApp/comments/hbjagc/dev_join_on_firefox_and_edge_available_for/
And here: https://www.reddit.com/r/JoinApp/comments/hx50sv/dev_desktop_app_custom_actions_command_line/
