### ISSUE TITLE
Not working on Microsoft Edge

### ISSUE THREAD

**Issue by dzg** [joaomgcd/JoinChrome#103]
After installing extension:

> _Join doesn't have any other devices available to send stuff to. Please log in on the same account on other devices to make them appear here._

If I open the extension:
![image](https://user-images.githubusercontent.com/466557/95241007-0ee6f900-07c2-11eb-890b-e0dd5fcbb4e4.png)

(Tried to register on Join Forum and never got confirmation email.)

**Comment by joaomgcd** [comment]
Hi. Edge is not supported, sorry. Only Chrome is.
