### ISSUE TITLE
Plugin doesnt connect in Opera

### ISSUE THREAD

**Issue by sonatamartica** [joaomgcd/JoinChrome#104]
Using Opera GX supports chrome extensions natively, but diagnostics gets stuck on Testing registration on Join's server...
any workaround? thanks, love your work <3

**Comment by joaomgcd** [comment]
Hi. Unfortunately Opera is not supported, sorry! It lacks an API that the Join extension needs for it to work. Maybe you can check out the Join Desktop app which is in beta right now? https://github.com/joaomgcd/JoinDesktop

Hope this helps
