### ISSUE TITLE
Battery level on Android TV device

### ISSUE THREAD

**Issue by mat4444** [joaomgcd/JoinChrome#105]
Hello,
Just to let you know that Android TV devices are reporting a wrong battery level (-2^31), since they are main power supplied.
Perhaps you could filter abnormal values and do not display them ?
![Sans titre](https://user-images.githubusercontent.com/53400792/97089108-e4a49080-1635-11eb-8302-da213e1816af.png)
Thanks !

**Comment by joaomgcd** [comment]
Thanks, fixed for next release! :)
