### ISSUE TITLE
this device: undefined

### ISSUE THREAD

**Issue by Androz2091** [joaomgcd/JoinChrome#106]
Hello :wave:

I installed Join on my Android phone (Huawei P Smart 2020) and logged into my Google account.
Then, I installed the Join Chrome extension using Brave on an Apple Silicon computer. I can log in, but:

- the device title is marked as `undefined`
- I can't see my phone device using the Chrome extension
- I can't see the Chrome extension device using my phone

![Capture d’écran 2020-11-25 à 14 17 25](https://user-images.githubusercontent.com/42497995/100232796-207a9080-2f29-11eb-92da-8a6e0bdb839a.png)

Thank you, let me know if you need more information!

**Comment by joaomgcd** [comment]
Hi. Unfortunately this extension doesn't work in Brave browser, sorry!

**Comment by Androz2091** [comment]
All right. Will it be supported one day?

**Comment by joaomgcd** [comment]
Maybe in the future, sorry! For now you could try this: https://joaoapps.com/join/desktop/

**Comment by stubar** [comment]
I followed the instructions here and join does work for Brave https://forum.joaoapps.com/index.php?threads/solved-add-brave-support-for-join.56076/.  However I have it on 2 laptops that use Brave, 1st works perfect, 2nd works but no notifications and the same undefined issue as OP.

**Comment by sillvva** [comment]
It also apparently doesn't work in MS Edge either. Same issue. This device: undefined

Unfortunately, the resolution for Brave doesn't work for Edge.

**Comment by stubar** [comment]
I managed to my 2nd laptop running Brave by simply removing the extension and re adding.  Only issue I have now is notifications don't work on this 2nd laptop.  The clipboard contents are being shared but I am unsure exactly when they are transferred.
