### ISSUE TITLE
Feature request: Persistent text in SMS field input

### ISSUE THREAD

**Issue by kdumovic** [joaomgcd/JoinChrome#11]
Loving this app and glad to see the Chrome extension got open-sourced!

One issue I've been having is that I'll halfway compose an SMS, return to a webpage (for instance to copy a link to paste into that text) and then click again to return to the Join popover and my halfway composed message is gone.

Is making them persistent an easy fix?

Cheers.

**Comment by joaomgcd** [comment]
Ok, fixed, thanks! :)
