### ISSUE TITLE
Everything works, but Diagnostics fails

### ISSUE THREAD

**Issue by hugalafutro** [joaomgcd/JoinChrome#110]
Hi,
I replaced my motherboard with the exact same model (so presumably the only change relevant to networking would be mac address change). If I run Join Diagnostics in chrome (Vivaldi) now, it fails the 2 steps related to receiving gcm pushes. I did the steps in the faq and the GCM recording events worked before deleting the folder and same after deleting it:
```
Sat May 08 2021 13:51:58 GMT+0100 (British Summer Time) | flejfacjooompmliegamfbpjjdlhokhj | 737484412860 | 674 | Data msg received
```
but in both cases Join diagnostics says this:
```
Getting account details... Success: Signed in with [REDACTED]@gmail.com: [REDACTED]
Testing registration on Join's server... Success: deviceId already existed. Updated existing device.
Refreshing Auth Token... Success: This is a secret so don't show it to anyone: token: [REDACTED]
Sending Push to server... Success!
Receiving Push from server... Didn't receive push after 5 seconds. Error: undefined: Try the steps mentioned in the FAQ here
Receiving Push with GCM key... Didn't receive push after 5 seconds. Error: undefined: Try the steps mentioned in the FAQ here
Comparing GCM keys... Success!
Testing popups... Success!
```

Now as the title mentioned, everything works, remote sms, pushing tabs, sending receiving files etc, but the errors bother me if something can't break down the line.

Any idea what I could do to get the diagnostics to succeed ?
Thanks!

**Comment by joaomgcd** [comment]
Hi. Are you maybe using the Join beta on your phone and so Join is communicating via local network?

**Comment by hugalafutro** [comment]
I am indeed using beta join on the phone android, however it all works even when off the network, I send few notes to the pc from the phone while at work today and received them all. The diagnostic on the pc still fails at only those 2 points.

I was thinking about removing the device and re-adding it, but would rather different solution (if possible) to somehow "reset" it while keeping the device_id as I use it in quite a few automations in Home Assistant.

**Comment by hugalafutro** [comment]
No, I mean I know it sounds weird, but I am sending from the phone (the wifi off) to the PC that claims it can't receive GCM pushes and it really works. If there is any way to obtain debug logs I'm happy to post them.

I just tried (from phone on 4G to the "faulty" PC on lan)
- send note
- speak
- send file

and they all worked. Or do those not use gcm? If not, what could I try that for sure uses gcm? 

Thanks!

**Comment by hugalafutro** [comment]
I've been doing the diagnostics every day since, and today the 2 checks show green again. Why? Nobody knows. Problem that solves itself though? I'll take it.

**Comment by joaomgcd** [comment]
😅 Weird, but ok, I'll take it! Glad it's working!
