### ISSUE TITLE
SMS text box doesn't scroll down all the way to the input line

### ISSUE THREAD

**Issue by beeflin** [joaomgcd/JoinChrome#111]
![Screenshot 2021-06-25 at 5 34 56 pm](https://user-images.githubusercontent.com/17083024/123457519-eb780e80-d5db-11eb-96c6-8c92e23bbde9.jpg)

See screenshot - this is as far down as it will scroll. 

MacOS Big Sur 20F71
Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by joaomgcd** [comment]
Hi. Do you maybe have zoom enabled? I tried on my Mac and it works normally. Try opening chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/options.html?tab=1 and check if it's at 100% zoom.

**Comment by beeflin** [comment]
I don't see a zoom control there, just Join options

By the way, it's not the Join drop-down SMS panel attached to the main Chrome window that's the problem, it's the unattached one that drops down from notification bubbles.

**Comment by joaomgcd** [comment]
The zoom options are in the Browser, not the page itself :) Do you see them there? Click menu on the top right > Zoom. Hope this helps.

**Comment by beeflin** [comment]
It seems to be on 100% but I'll have to test it by receiving a text and getting a notification. I'll get back to you after that.

**Comment by joaomgcd** [comment]
Thanks!

**Comment by tommyent** [comment]
@joaomgcd so I had the same problem and went to debug it with the git repo. It only seems to happen with the Chrome store version. So it seems you should be able to just bump the version to fix it.

**Comment by beeflin** [comment]
I'm not a programmer and only a casual member of GitHub. I've downloaded the GitHub Mac repository app but need to know how to use it to install Join. Can someone instruct me?

**Comment by tommyent** [comment]
You actually don't need that. Remove Join from Chrome
Click the green "code" button. 
<img width="1674" alt="Screen Shot 2021-07-01 at 5 04 24 PM" src="https://user-images.githubusercontent.com/509970/124189270-764e8280-da8e-11eb-8af0-76846c74d7c8.png">
Download the zip to where you want it. Unzip and then go to 

chrome://extensions/

In your browser and select load unpacked 
<img width="1674" alt="Screen Shot 2021-07-01 at 5 06 22 PM" src="https://user-images.githubusercontent.com/509970/124189526-df35fa80-da8e-11eb-9fe6-1f114bdeda07.png">
Choose the folder you downloaded. 

Issue with this is you will need to manually update but you will probably be able to switch back to the Chrome Store version once he bumps the number. If you stay with the repo I can explain how to update with the Github app.

**Comment by beeflin** [comment]
Thank you so much!

**Comment by joaomgcd** [comment]
Does that mean that it also worked for you @beeflin ? :)

**Comment by beeflin** [comment]
I haven't tested it yet but will soon, and get back to you.

**Comment by beeflin** [comment]
Yes! just received an SMS message and the reply field was OK! Thank you.
