### ISSUE TITLE
No SMS in Chrome extension but SMS show up in Join on the Web

### ISSUE THREAD

**Issue by coman49** [joaomgcd/JoinChrome#126]
Just installed everything for the first time. Set up the Android app. Went to Join on the Web in Chrome browser on the phone, SMS show up there fine. Installed Chrome extension on Windows 10, but there's no SMS tab and no SMS option under the phone device. Diagnostics all ran green on both the Android app and the Windows 10 Chrome extension.

**Comment by joaomgcd** [comment]
You have to select a device from the devices tab and then press the "Send an SMS Message" button there.

Hope this helps!

**Comment by coman49** [comment]
> You have to select a device from the devices tab and then press the "Send an SMS Message" button there.
> 
> Hope this helps!

Right, but that button is not there. Attached screenshots showing this. 

![Screenshot 2023-11-21 110256](https://github.com/joaomgcd/JoinChrome/assets/28886182/d73f1a20-26c6-404d-9ddc-bd4a0783430e)
![Screenshot 2023-11-21 110335](https://github.com/joaomgcd/JoinChrome/assets/28886182/e33d951d-82ab-4d33-afec-c1db9230aeea)

**Comment by joaomgcd** [comment]
Thanks for clarifying! Ok, it was an issue with the detection of SMS ability :)

Can you please try [this version](https://drive.google.com/file/d/18V276YwSlfc3voV1s-SUxdCfoP9fCerp/view?usp=sharing)?
