### ISSUE TITLE
Text shadow

### ISSUE THREAD

**Issue by tommyent** [joaomgcd/JoinChrome#14]
Is there a reason why the legacy text shadow is still being used on #appname ?
![screen shot 2016-06-30 at 8 49 06 am](https://cloud.githubusercontent.com/assets/509970/16488732/f2fbd08e-3e9f-11e6-9f3b-747358ac77f6.png)

**Comment by joaomgcd** [comment]
Because of my aesthetic incompetence? :D

**Comment by tommyent** [comment]
😄  just wasn't sure if it made it easier to read in some case

**Comment by joaomgcd** [comment]
If you find a way to make it just as readable and look better I'm all for it! :+1:

**Comment by tommyent** [comment]
I think just removing the shadow it's still readable. Just posted a poll to make sure it works for the majority.
