### ISSUE TITLE
Feature Request: Don't open URLs automatically.

### ISSUE THREAD

**Issue by Busimus** [joaomgcd/JoinChrome#16]
I do not want Join to automatically open all URLs I send to Chrome, it's annoying in many ways. 
I want it to just leave them as a notification, but the Android app has no option to send URLs like that (even if you garble them, Join on Chrome still tries to open an intentionally broken URL, which results in an error page).

I would greatly appreciate this feature. Save me from this suffering.

**Comment by joaomgcd** [comment]
How would you suggest this to be implemented? Thanks

**Comment by Busimus** [comment]
Basically like this: https://github.com/joaomgcd/JoinChrome/pull/17

**Comment by joaomgcd** [comment]
Thanks very much! :) Accepted.
