### ISSUE TITLE
Css is messed up on older chrome version because of use of css var()

### ISSUE THREAD

**Issue by jamieisboss** [joaomgcd/JoinChrome#21]
Installed join on a new pc today, the css is all weird, colours are missing:

![image](https://cloud.githubusercontent.com/assets/5108847/17301408/d24fd4e2-580e-11e6-9283-497d2d3c43aa.png)

inspected the css:

![image](https://cloud.githubusercontent.com/assets/5108847/17301498/4d8fad12-580f-11e6-9ba5-3f89a11ae5f2.png)

Can see you're using var(), this is a University PC so chrome 47 is the newest version and i cant do a whole bunch about it, maybe a bit early to be [using what's still an experimental feature](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)? I appreciate 47 is a pretty old version of chrome as chrome versions go, but it's still only 6 months old so maybe a fallback would be appropriate.

Either way, reporting so you know.

J

**Comment by mrkevinlin** [comment]
Yup. I've been considering switching it back for a while now because it is jumping the gun a little. Your issue request may be the impetus necessary. Thanks!

**Comment by tommyent** [comment]
That's 5 versions and 8 months :(  makes me sad that places are still doing this with a browser.  You'd figure the security risk would outweigh anything else.

Fallback wouldn't really exist other than declaring the color again as far as I know and obviously that defeats the purpose. Personally I'm not 100% sold on the use of native vars yet (probably never on syntax) and would much rather use a preprocessor for variables. My vote would be SASS. However the projects not that big so good ole' fashioned hex is not that big a deal.

How it renders is pretty crazy.

**Comment by joaomgcd** [comment]
Kevin or Tom, are you on it? :) Or should I?

**Comment by tommyent** [comment]
I can do it if you want

**Comment by mrkevinlin** [comment]
Go ahead with it I'm unfortunately on a trip right now

**Comment by joaomgcd** [comment]
Ok Tom, I appreciate it if you can do it :) I always like to take care of other non-visual stuff. Thanks in advance!

**Comment by tommyent** [comment]
Ok should be all set

**Comment by joaomgcd** [comment]
Thank you very much! :) Merged
