### ISSUE TITLE
Groupme Notifications

### ISSUE THREAD

**Issue by grpace** [joaomgcd/JoinChrome#24]
Would love an option when you get a Groupme notification to bring you to https://web.groupme.com/chats

**Comment by mrkevinlin** [comment]
This should be possible to implement yourself! If you go to the Settings page and the Advanced tab as shown below, you should be able to specify your request exactly. You'll just have to figure out the package name that Groupme uses.

![image](https://cloud.githubusercontent.com/assets/6395291/18176265/783c186e-703a-11e6-8410-bacb8ec37c61.png)

**Comment by grpace** [comment]
Wow this is great. Thank you.
