### ISSUE TITLE
Facebook Messenger SMS

### ISSUE THREAD

**Issue by grpace** [joaomgcd/JoinChrome#25]
Would be really cool feature to be able to detect when a notification from Facebook messenger is just an SMS and not bring you to the https://www.messenger.com but rather open a reply alert.

**Comment by salimnanji** [comment]
+1. Would be so useful!

**Comment by joaomgcd** [comment]
Unfortunately a notification is just a notification. I don't have a way of knowing if that notification corresponds to an SMS or not, sorry!
