### ISSUE TITLE
issue while testing

### ISSUE THREAD

**Issue by Jonathan34** [joaomgcd/JoinChrome#33]
I am having issues with the chrome plug-in (Chrome v56 dev).
When i test using the Diagnostics tab:
![2016-11-07_11h39_16](https://cloud.githubusercontent.com/assets/3976137/20068634/f462cca2-a4de-11e6-8996-8b079305f880.png)

When i want to rename a device (the chrome) one, nothing happens when i click the button.

When i want to send a page /download to my mobile device, nothing happens either.

I uninstalled the chrome plugin and reinstalled. no effect.

**Comment by Jonathan34** [comment]
I ran the diagnostics on my android phone, it complained about some GCM token being invalid. App suggested to reset them and it works fine since.

I cannot still rename a device from the chrome plug-in but the major issue is gone.

**Comment by tommyent** [comment]
@joaomgcd While looking at this I noticed detached_panel has been deprecated. Submitting a pull request now

**Comment by joaomgcd** [comment]
This is fixed with the latest fix from @tommyent ! Thanks!
