### ISSUE TITLE
Chrome extension doesn't load devices and therefore is broken

### ISSUE THREAD

**Issue by tseven** [joaomgcd/JoinChrome#37]
For some reason, no devices are loaded in the chrome extension.

The following error shows up in the console:
`Uncaught TypeError: Cannot read property 'where' of null
    at HTMLDocument.<anonymous> (chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/options.js:266:29)`

The extension's setting page shows the device as "undefined" and no photo for the avatar.
I am able to access all the features through the website at: https://joinjoaomgcd.appspot.com/

I haven't dug into the code enough to pinpoint the issue, but a guess is that the extension is not handling multiple google account sign-ins properly. I'm currently signed into 4 google accounts.

I have downloaded the latest source code for the extension and loaded it manually and get the same error message and result.

I am running Chrome Version 54.0.2840.98 (64-bit) on macOS Sierra

![w_43](https://cloud.githubusercontent.com/assets/311287/20540762/4997f61c-b0af-11e6-9708-25105513011d.png)

**Comment by joaomgcd** [comment]
Can you please try this:
- go into Chrome
- settings
- extensions
- click on join.html
- go to the console tab
- see if any error appears there

Thanks!

**Comment by tseven** [comment]
I didn't see a link or reference to "join.html" on the extensions page.
![w_45](https://cloud.githubusercontent.com/assets/311287/20572962/8c0192de-b162-11e6-8656-3a95eb7c460f.png)

Clicking "options" opened the settings in a model.
I pulled up the console for that, and I am getting the same error.
![w_44](https://cloud.githubusercontent.com/assets/311287/20572986/a0818bb0-b162-11e6-81df-42f941a1169b.png)


I uninstalled and re-installed the extension before doing this.

**Comment by tseven** [comment]
I manually browsed to the plugin's join.html
chrome-extension://flejfa...okhj/join.html

And got this error in console:
`Error getting key: Asynchronous operation is pending.   join.js:1437`

**Comment by joaomgcd** [comment]
Oh, ok. Please follow the procedure here: https://joaoapps.com/join/faq/

Let me know how it goes!

**Comment by tseven** [comment]
Which procedure exactly?

**Comment by joaomgcd** [comment]
The one under the question **Why can’t I receive pushes on the Chrome extension?**

**Comment by tseven** [comment]
Got it, it's a little misleading since the entire extension wasn't working, not just "pushes".

The steps I needed to fix the issue was:
1. Delete/rename the GCM Store folder.
2. Restart chrome.
3. Verify I was connected on: chrome://gcm-internals/ -- The extension was not working at this point.
4. Remove and re-install extension.

Thanks for your help.
Perhaps you could update the FAQ to include the fix for this issue as well?

**Comment by joaomgcd** [comment]
Thanks! Updated the question title now :) Glad you got it to work!
