### ISSUE TITLE
Perform Favorite Command shortcut does not work.

### ISSUE THREAD

**Issue by xersace** [joaomgcd/JoinChrome#38]
The Perform Favorite Command shortcut does not work, but the shortcuts for all the other configurations do work.

**Comment by joaomgcd** [comment]
Did you configure what the command is supposed to do in the settings? What did  you configure it to do?

**Comment by xersace** [comment]
Yeah, I configured it properly to Ctrl-Shrift-X, and it isn't triggering the action. I tried to see if I did it wrong, but I configured the same keys to 'Repeat Last Command', 'Show a Popup' and 'Perform your voice command' and they all work properly. Except for 'Perform Your Favorite Command Chose below'

All I'm trying to do is use the hotkey to send my current Chrome tab to my phone.

**Comment by joaomgcd** [comment]
But you did configure your favorite command to be the "Send Current Tab" command, correct?

**Comment by xersace** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17373527/21528145/587cb760-ccfe-11e6-9f85-bcf812a7b029.png)

**Comment by joaomgcd** [comment]
Can you please try selecting any other command and then the "Send current tab" command again from that dropdown? I think it's a bug related to you not ever having changed that dropdown value :)
