### ISSUE TITLE
Can't receive sms notifications 

### ISSUE THREAD

**Issue by Cabeda** [joaomgcd/JoinChrome#40]
I had set the facebook messenger as the default app for SMS but I've since returned to a dedicated app. But I don't receive notifications on chrome when I receive new SMS (I need to click on the refresh button). Do you know what I'm doing wrong?

**Comment by joaomgcd** [comment]
Can you please run the diagnostics in the chrome extension option and see if it all works? Thanks

**Comment by Cabeda** [comment]
Yes, the diagnostics runs everything correctly

**Comment by joaomgcd** [comment]
It does not, if you have the notification sync service running. Is the SMS service on your android device maybe not enabled? Check in the Join android app -> Settings -> SMS and Phone Calls. Thanks!

**Comment by Cabeda** [comment]
I've reenabled the options again (just to be sure) it isn't working. I receive the SMS but I have to manually refresh  the tab

**Comment by joaomgcd** [comment]
Sorry about that. Can you please try this version? https://dl.dropboxusercontent.com/u/9787157/apk/Join.apk

After you receive an SMS message please post the logs here so I can try to figure out why it isn't pushing the notification. Thanks in advance!

**Comment by Cabeda** [comment]
version 1.5.1

 OS Build MHC19Q
 OS Code 23
 Device A0001
 Manufacturer OnePlus
 Product bacon

SMS - 2017-03-02 00:03:35.627 - Detected change in SMS db
SMS - 2017-03-02 00:03:34.763 - Uploading Last SMS Messages...
SMS - 2017-03-02 00:03:34.750 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 00:03:34.690 - Set last SMS date to 2017-03-02 00:03:33
SMS - 2017-03-02 00:03:34.648 - Found 1 new SMS starting at date 2017-03-02 00:03:33 and ending at 2017-03-02 00:03:33
SMS - 2017-03-02 00:03:34.552 - Detected change in SMS db
SMS - 2017-03-02 00:03:33.941 - Detected change in SMS db
SMS - 2017-03-02 00:03:21.056 - Detected change in SMS db
SMS - 2017-03-01 23:58:44.588 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-01 23:58:44.581 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-01 23:58:44.576 - Sending push for SMS from Joana <3
SMS - 2017-03-01 23:58:44.571 - Notifying other devices of new SMS from Joana <3 
SMS - 2017-03-01 23:58:44.467 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:58:44.448 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:58:44.392 - Set last SMS date to 2017-03-01 23:58:41
SMS - 2017-03-01 23:58:44.359 - Found 1 new SMS starting at date 2017-03-01 23:58:41 and ending at 2017-03-01 23:58:41
SMS - 2017-03-01 23:58:41.839 - Detected change in SMS db
SMS - 2017-03-01 23:58:41.573 - Detected change in SMS db
SMS - 2017-03-01 23:56:52.137 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:56:52.113 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:56:49.618 - Set last SMS date to 2017-03-01 23:56:48
SMS - 2017-03-01 23:56:49.566 - Found 1 new SMS starting at date 2017-03-01 23:56:48 and ending at 2017-03-01 23:56:48
SMS - 2017-03-01 23:56:48.840 - Detected change in SMS db
Push - 2017-03-01 23:56:48.145 - Sending SMS to number +351914242161: Podes mandar uma mensagem? Preciso de testar uma coisa
SMS - 2017-03-01 23:42:07.752 - Detected change in SMS db
SMS - 2017-03-01 23:42:07.192 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:42:07.176 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:42:07.128 - Set last SMS date to 2017-03-01 23:42:06
SMS - 2017-03-01 23:42:07.082 - Found 1 new SMS starting at date 2017-03-01 23:42:06 and ending at 2017-03-01 23:42:06
SMS - 2017-03-01 23:42:06.955 - Detected change in SMS db
SMS - 2017-03-01 23:42:06.400 - Detected change in SMS db
SMS - 2017-03-01 23:41:52.496 - Detected change in SMS db
SMS - 2017-03-01 23:40:35.687 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:40:35.655 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:40:35.575 - Set last SMS date to 2017-03-01 23:40:30
SMS - 2017-03-01 23:40:35.516 - Found 1 new SMS starting at date 2017-03-01 23:40:30 and ending at 2017-03-01 23:40:30
SMS - 2017-03-01 23:40:35.341 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-01 23:40:35.330 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-01 23:40:35.316 - Sending push for SMS from Joana <3
SMS - 2017-03-01 23:40:35.302 - Notifying other devices of new SMS from Joana <3
SMS - 2017-03-01 23:40:31.469 - Detected change in SMS db
SMS - 2017-03-01 23:40:30.838 - Detected change in SMS db
SMS - 2017-03-01 23:33:51.057 - Detected change in SMS db
SMS - 2017-03-01 23:33:50.018 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:33:50.002 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:33:49.946 - Set last SMS date to 2017-03-01 23:33:49
SMS - 2017-03-01 23:33:49.897 - Found 1 new SMS starting at date 2017-03-01 23:33:49 and ending at 2017-03-01 23:33:49
SMS - 2017-03-01 23:33:49.710 - Detected change in SMS db
SMS - 2017-03-01 23:33:49.124 - Detected change in SMS db
SMS - 2017-03-01 23:32:19.519 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-01 23:32:16.318 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-01 23:32:14.962 - Detected change in SMS db
SMS - 2017-03-01 23:32:13.361 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:32:13.329 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:32:13.248 - Set last SMS date to 2017-03-01 23:32:07
SMS - 2017-03-01 23:32:13.205 - Found 1 new SMS starting at date 2017-03-01 23:32:07 and ending at 2017-03-01 23:32:07
SMS - 2017-03-01 23:32:12.892 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-01 23:32:12.882 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-01 23:32:12.873 - Sending push for SMS from Joana <3
SMS - 2017-03-01 23:32:12.861 - Notifying other devices of new SMS from Joana <3
SMS - 2017-03-01 23:32:11.742 - Detected change in SMS db
SMS - 2017-03-01 23:32:07.638 - Detected change in SMS db
Services - 2017-03-01 23:27:54.680 - Starting background services if needed...
Join - 2017-03-01 23:27:50.215 - Started
SMS - 2017-03-01 23:27:49.561 - Attaching GSM listeners...
Push - 2017-03-01 23:27:04.612 - Open directly: true
Encryption - 2017-03-01 23:27:04.576 - Error decrypting: java.lang.IllegalArgumentException: bad base-64
SMS - 2017-03-01 23:25:58.643 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:25:58.635 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:25:58.593 - Set last SMS date to 2017-03-01 23:25:57
SMS - 2017-03-01 23:25:58.529 - Found 1 new SMS starting at date 2017-03-01 23:25:57 and ending at 2017-03-01 23:25:57
SMS - 2017-03-01 23:25:57.916 - Detected change in SMS db
Push - 2017-03-01 23:25:57.552 - Sending SMS to number +351914242161: Espero que esteja tudo bem
SMS - 2017-03-01 23:25:51.804 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:25:51.793 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:25:51.754 - Set last SMS date to 2017-03-01 23:25:51
SMS - 2017-03-01 23:25:51.709 - Found 1 new SMS starting at date 2017-03-01 23:25:51 and ending at 2017-03-01 23:25:51
SMS - 2017-03-01 23:25:51.071 - Detected change in SMS db
Push - 2017-03-01 23:25:50.555 - Sending SMS to number +351914242161: Já te telefono
SMS - 2017-03-01 23:25:46.714 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:25:46.701 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:25:46.678 - Set last SMS date to 2017-03-01 23:25:45
SMS - 2017-03-01 23:25:46.661 - Found 1 new SMS starting at date 2017-03-01 23:25:45 and ending at 2017-03-01 23:25:45
SMS - 2017-03-01 23:25:46.628 - Detected change in SMS db
Push - 2017-03-01 23:25:46.607 - Sending SMS to number +351914242161:  dito nada
SMS - 2017-03-01 23:25:43.252 - Uploading Last SMS Messages...
SMS - 2017-03-01 23:25:43.236 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 23:25:43.194 - Set last SMS date to 2017-03-01 23:25:42
SMS - 2017-03-01 23:25:43.067 - Found 1 new SMS starting at date 2017-03-01 23:25:42 and ending at 2017-03-01 23:25:42
SMS - 2017-03-01 23:25:42.341 - Detected change in SMS db
Push - 2017-03-01 23:25:41.817 - Sending SMS to number +351914242161: Estas aulas são de dar em doido
SMS - 2017-03-01 22:24:29.894 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-01 22:24:29.882 - Sending push for SMS from Joana <3
SMS - 2017-03-01 22:24:29.853 - Notifying other devices of new SMS from Joana <3
SMS - 2017-03-01 22:24:29.540 - Uploading Last SMS Messages...
SMS - 2017-03-01 22:24:29.523 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-01 22:24:29.457 - Set last SMS date to 2017-03-01 22:23:35
SMS - 2017-03-01 22:24:29.347 - Found 1 new SMS starting at date 2017-03-01 22:23:35 and ending at 2017-03-01 22:23:35
SMS - 2017-03-01 22:23:36.077 - Detected change in SMS db
SMS - 2017-03-01 22:23:35.809 - Detected change in SMS db

**Comment by joaomgcd** [comment]
Thanks, that helped. Can you please try going in the Android app's settings -> SMS And phone calls and try to block at least one device from receiving SMS notifications? Thanks!

**Comment by Cabeda** [comment]
It worked! 

 version 1.5.1

 OS Build MHC19Q
 OS Code 23
 Device A0001
 Manufacturer OnePlus
 Product bacon

Push - 2017-03-02 11:44:12.619 - Open directly: true
Encryption - 2017-03-02 11:44:12.552 - Error decrypting: java.lang.IllegalArgumentException: bad base-64
SMS - 2017-03-02 11:42:51.576 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-02 11:42:51.419 - Uploading Last SMS Messages...
SMS - 2017-03-02 11:42:51.413 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 11:42:51.367 - All devices :7ca488a120d24750a27dac737085a3d7=Chrome-ASUS,e06d4239666b495b9695859a977e4275=Chrome-Armis,1ea57266d0be4baca15e668d1ca23f9b=Chrome-HOME
SMS - 2017-03-02 11:42:51.358 - Got devices to send to :e06d4239666b495b9695859a977e4275
SMS - 2017-03-02 11:42:51.350 - Got devices not to send to :1ea57266d0be4baca15e668d1ca23f9b,7ca488a120d24750a27dac737085a3d7
SMS - 2017-03-02 11:42:51.332 - Set last SMS date to 2017-03-02 11:42:45
SMS - 2017-03-02 11:42:51.331 - Sending push for SMS from Joana <3
SMS - 2017-03-02 11:42:51.309 - Notifying other devices of new SMS from Joana <3
SMS - 2017-03-02 11:42:51.280 - Found 1 new SMS starting at date 2017-03-02 11:42:45 and ending at 2017-03-02 11:42:45
SMS - 2017-03-02 11:42:46.396 - Detected change in SMS db
SMS - 2017-03-02 11:42:45.992 - Detected change in SMS db
SMS - 2017-03-02 11:36:55.226 - Detected change in SMS db
SMS - 2017-03-02 11:36:54.836 - Uploading Last SMS Messages...
SMS - 2017-03-02 11:36:54.821 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 11:36:54.770 - Set last SMS date to 2017-03-02 11:36:54
SMS - 2017-03-02 11:36:54.730 - Found 1 new SMS starting at date 2017-03-02 11:36:54 and ending at 2017-03-02 11:36:54
SMS - 2017-03-02 11:36:54.689 - Detected change in SMS db
SMS - 2017-03-02 11:36:54.114 - Detected change in SMS db
SMS - 2017-03-02 11:33:59.454 - Detected change in SMS db
SMS - 2017-03-02 11:29:47.384 - Uploading Last SMS Messages...
SMS - 2017-03-02 11:29:47.370 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 11:29:47.354 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-02 11:29:47.340 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-02 11:29:47.328 - Sending push for SMS from Joana <3
SMS - 2017-03-02 11:29:47.320 - Notifying other devices of new SMS from Joana <3
SMS - 2017-03-02 11:29:47.272 - Set last SMS date to 2017-03-02 11:29:41
SMS - 2017-03-02 11:29:47.243 - Found 1 new SMS starting at date 2017-03-02 11:29:41 and ending at 2017-03-02 11:29:41
SMS - 2017-03-02 11:29:41.749 - Detected change in SMS db
SMS - 2017-03-02 11:29:41.363 - Detected change in SMS db
SMS - 2017-03-02 11:23:20.232 - Detected change in SMS db
SMS - 2017-03-02 11:23:19.377 - Uploading Last SMS Messages...
SMS - 2017-03-02 11:23:19.361 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 11:23:19.298 - Set last SMS date to 2017-03-02 11:23:18
SMS - 2017-03-02 11:23:19.244 - Found 1 new SMS starting at date 2017-03-02 11:23:18 and ending at 2017-03-02 11:23:18
SMS - 2017-03-02 11:23:19.119 - Detected change in SMS db
SMS - 2017-03-02 11:23:18.558 - Detected change in SMS db
SMS - 2017-03-02 11:22:57.736 - Detected change in SMS db
SMS - 2017-03-02 11:15:08.929 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-02 11:15:08.923 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-02 11:15:08.919 - Sending push for SMS from Joana <3
SMS - 2017-03-02 11:15:08.910 - Notifying other devices of new SMS from Joana <3
SMS - 2017-03-02 11:15:08.739 - Uploading Last SMS Messages...
SMS - 2017-03-02 11:15:08.706 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 11:15:08.654 - Set last SMS date to 2017-03-02 11:15:04
SMS - 2017-03-02 11:15:08.594 - Found 1 new SMS starting at date 2017-03-02 11:15:04 and ending at 2017-03-02 11:15:04
SMS - 2017-03-02 11:15:04.957 - Detected change in SMS db
SMS - 2017-03-02 11:15:04.536 - Detected change in SMS db
SMS - 2017-03-02 11:01:37.937 - Uploading Last SMS Messages...
SMS - 2017-03-02 11:01:37.919 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 11:01:32.342 - Set last SMS date to 2017-03-02 11:01:31
SMS - 2017-03-02 11:01:32.308 - Found 1 new SMS starting at date 2017-03-02 11:01:31 and ending at 2017-03-02 11:01:31
SMS - 2017-03-02 11:01:31.426 - Detected change in SMS db
Push - 2017-03-02 11:01:30.510 - Sending SMS to number +351914242161: Gosto
SMS - 2017-03-02 10:23:05.373 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-02 10:23:05.365 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-02 10:23:05.358 - Sending push for SMS from Joana <3
SMS - 2017-03-02 10:23:05.349 - Uploading Last SMS Messages...
SMS - 2017-03-02 10:23:05.345 - Notifying other devices of new SMS from Joana <3
SMS - 2017-03-02 10:23:05.318 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 10:23:05.235 - Set last SMS date to 2017-03-02 10:23:02
SMS - 2017-03-02 10:23:05.182 - Found 1 new SMS starting at date 2017-03-02 10:23:02 and ending at 2017-03-02 10:23:02
SMS - 2017-03-02 10:23:02.964 - Detected change in SMS db
SMS - 2017-03-02 10:23:02.635 - Detected change in SMS db
SMS - 2017-03-02 10:13:29.690 - Uploading Last SMS Messages...
SMS - 2017-03-02 10:13:29.670 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 10:13:29.602 - Set last SMS date to 2017-03-02 10:13:28
SMS - 2017-03-02 10:13:29.558 - Found 1 new SMS starting at date 2017-03-02 10:13:28 and ending at 2017-03-02 10:13:28
SMS - 2017-03-02 10:13:28.853 - Detected change in SMS db
Push - 2017-03-02 10:13:28.432 - Sending SMS to number +351914242161: Mas não 
SMS - 2017-03-02 10:13:21.053 - Uploading Last SMS Messages...
SMS - 2017-03-02 10:13:21.032 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 10:13:20.973 - Set last SMS date to 2017-03-02 10:13:19
SMS - 2017-03-02 10:13:20.926 - Found 1 new SMS starting at date 2017-03-02 10:13:19 and ending at 2017-03-02 10:13:19
SMS - 2017-03-02 10:13:19.981 - Detected change in SMS db
Push - 2017-03-02 10:13:19.533 - Sending SMS to number +351914242161: Dorm
SMS - 2017-03-02 10:13:17.593 - Uploading Last SMS Messages...
SMS - 2017-03-02 10:13:17.577 - Uploading SMS Messages for +351914242161...
SMS - 2017-03-02 10:13:17.514 - Set last SMS date to 2017-03-02 10:13:16
SMS - 2017-03-02 10:13:17.457 - Found 1 new SMS starting at date 2017-03-02 10:13:16 and ending at 2017-03-02 10:13:16
SMS - 2017-03-02 10:13:16.766 - Detected change in SMS db
Push - 2017-03-02 10:13:16.163 - Sending SMS to number +351914242161: Não és nada!!! 
SMS - 2017-03-02 10:04:34.220 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-02 10:04:34.211 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-02 10:04:34.202 - Sending push for SMS from 477
SMS - 2017-03-02 10:04:34.200 - Notifying other devices of new SMS from 477
SMS - 2017-03-02 10:04:34.061 - Uploading Last SMS Messages...
SMS - 2017-03-02 10:04:34.045 - Uploading SMS Messages for IPS...
SMS - 2017-03-02 10:04:33.963 - Set last SMS date to 2017-03-02 10:04:27
SMS - 2017-03-02 10:04:33.902 - Found 1 new SMS starting at date 2017-03-02 10:04:27 and ending at 2017-03-02 10:04:27
SMS - 2017-03-02 10:04:28.049 - Detected change in SMS db
SMS - 2017-03-02 10:04:27.747 - Detected change in SMS db
SMS - 2017-03-02 10:03:35.571 - Exporting SMS from broadcast after 1 second
SMS - 2017-03-02 10:03:35.553 - Uploading Last SMS Messages...
SMS - 2017-03-02 10:03:35.545 - Got devices to send to old:175467684c16417b87eb289c77c507e2,41f301b9dc444cce9b9da7cb296a4da4,80bcb2d9d9f3405a85490a69c2e02ad2,9b6132d4f72144479f1604993ec2ce21,a000a86defc34aef845ea7e00ee83ec5,d1a2ecec9baf4c9db1d6400d6bb50c1b,8640d65e413749e4b110a22fc38ae08a
SMS - 2017-03-02 10:03:35.534 - Notifying other devices of new SMS from Joana <3
SMS - 2017-03-02 10:03:35.534 - Sending push for SMS from Joana <3
SMS - 2017-03-02 10:03:35.514 - Uploading SMS Messages for +351914242161...

**Comment by joaomgcd** [comment]
Great! :) Glad to help!
