### ISSUE TITLE
Link to correct Google Inbox

### ISSUE THREAD

**Issue by sQVe** [joaomgcd/JoinChrome#41]
Firstly I would like to give a **huge thank you** for the app. I've just used it a couple of days but already enjoying it immensely.

I juggle on a daily basis around **6 Google Inbox** account and when I get an notification I'd like it to open the correct Inbox, **not the default account**. It's confusing and slightly annoying.

Have I missed something that I need to configure or is this feature missing? If so would it be possible to implement this feature?

Cheers again!

**Comment by joaomgcd** [comment]
Unfortunately that's not something I can implement, sorry! I have no way of knowing which inbox link corresponds to each notification. Sorry, wish I could help!

**Comment by sQVe** [comment]
I thought that might be the case @joaomgcd. Too bad.

Is there a way to change so the notifications open an external program, say Nylas Mail, instead of going to the Google Inbox URL? That would also solve my issue.

**Comment by joaomgcd** [comment]
If that external program can be opened via a URL you can configure it in the extension options under advanced. Hope this helps!
