### ISSUE TITLE
Join Server Problem

### ISSUE THREAD

**Issue by Cabeda** [joaomgcd/JoinChrome#42]
I've run a diagnostic and I can't connect to Join server. Do you know what's happening?

![screenshot_1](https://cloud.githubusercontent.com/assets/8181056/23794262/3743b384-0587-11e7-958c-69247c3af440.png)

**Comment by joaomgcd** [comment]
Did you sign in when first installing the extension?

**Comment by Cabeda** [comment]
First thing I've done

**Comment by joaomgcd** [comment]
Are you still having the same issue?

**Comment by Cabeda** [comment]
Sorry, forgot to come here. On Sunday it started working :-)

**Comment by joaomgcd** [comment]
Great :)
