### ISSUE TITLE
Google Chrome is using your microphone bug

### ISSUE THREAD

**Issue by docsiswantsthis** [joaomgcd/JoinChrome#43]
A microphone icon appears with the text "Google Chrome is using your microphone, Join" on my mac's top toolbar. Voice Control is disabled under Join's options.

<img width="517" alt="screen shot 2017-03-12 at 6 15 11 pm" src="https://cloud.githubusercontent.com/assets/22192415/23833550/4226d0a4-0750-11e7-81a7-92557af7991d.png">
<img width="315" alt="screen shot 2017-03-12 at 6 14 53 pm" src="https://cloud.githubusercontent.com/assets/22192415/23833549/42263f68-0750-11e7-88ef-6b5e0e81e57c.png">

**Comment by andrew-kennedy** [comment]
I have this same problem, just wanted to bump this issue.

**Comment by andrew-kennedy** [comment]
@joaomgcd I still get this issue with every single text and it's mildly annoying as I also have an app notify me when my microphone is being used (Micro Snitch) and join does not release it's hold on the microphone until you open it by clicking it's chrome extension button. I believe it's triggered [here](https://github.com/joaomgcd/JoinChrome/blob/f19c59fdc9e35bc610819a122b265ff05359aebd/js/gcm.js#L725) when the gcm notification comes in. Whenever I call that same method in the developer console when I debug the join extension, the mic becomes "active" and I have to open the main Join panel to get it to release it's mic hold.

**Comment by docsiswantsthis** [comment]
I second this. Please fix this @joaomgcd . Even if it's a bug, it's a bit creepy to see that "Google Chrome is using my microphone, Join" several times per day.

**Comment by joaomgcd** [comment]
Thanks for the info! I'll try to fix this ASAP!

**Comment by andrew-kennedy** [comment]
No, all voice options are disabled

**Comment by tommyent** [comment]
I reported I think on Github that the most recent beta at the time was not doing this but unfortunately it's back

**Comment by CCninja86** [comment]
I agree that it could be that the .isMicAvailable() method is triggering it, because obviously it has to access the microphone to know if it's available.

**Comment by andrew-kennedy** [comment]
@CCninja86 yeah, but my comment was more to point out that it's triggered within that particular context (since doing a search for isMicAvailable in the repo led to quite a few results) in case that was useful.

Even if it has to access the microphone to know if it's available, it shouldn't even be checking if it is available if the mic features are totally disabled.

**Comment by docsiswantsthis** [comment]
Any updates @joaomgcd ?

Thanks in advance :)

**Comment by joaomgcd** [comment]
Sorry I haven't had time to boot up the mac to check this bug, sorry! Need to get on it...

**Comment by joaomgcd** [comment]
This should be fixed now. Thanks @yut23 !!
