### ISSUE TITLE
SMS/Contacts not working on the Chrome app

### ISSUE THREAD

**Issue by arcooke** [joaomgcd/JoinChrome#44]
Not sure what to make of this.  The SMS feature of the chrome app seems entirely nonfunctional for me.  It doesn't search or list any of my contacts.  Yet all systems are go in the diagnostics of both the Android app and the chrome app.

Chrome app is 1.5.3. 
Android is beta 1.5.2b.bf
I use Textra for texting but otherwise the phone is totally stock.. brand new Nexus 6P

![image](https://cloud.githubusercontent.com/assets/6278400/23907834/45725bc4-08a0-11e7-941d-3b59211758cc.png)

Sync contacts/SMS successful

![image](http://i.imgur.com/j22as2Y.png)

Everything in Chrome passes

![image](http://i.imgur.com/xQA7olk.png)

**Comment by arcooke** [comment]
OK well I managed to get this fixed shortly after posting.

All it took was for one person to send me a text.  Once I received their text, all of my SMS/Contacts filled out properly.  That received text triggered some kind of update in the chrome app that wasn't being done when I clicked the refresh button.

**Comment by joaomgcd** [comment]
Thanks for the feedback. Maybe the files on your google drive were deleted before? If this happens again try disabling and re-enabling the SMS service in the Android app. Thanks!
