### ISSUE TITLE
Tabs are a little cramped

### ISSUE THREAD

**Issue by mrkevinlin** [joaomgcd/JoinChrome#48]
Several updates ago, the spacing between the tabs of the extension was reduced, making it feel just a little cramped.

What do you think of increasing the padding on each side back to 8px and shortening the SMS/Phone tab to say "Contacts" only? I think it is a pretty good compromise. It is essentially a list of the most commonly contacted people with their recent messages AND with the option to phone them directly.

http://imgur.com/a/xP5LO

**Comment by tommyent** [comment]
Why do this vs increase the size of the container and the padding? 

This is on my MBA 1440 x 900

![screen shot 2017-04-03 at 8 35 24 pm](https://cloud.githubusercontent.com/assets/509970/24637243/a6df1ec0-18ad-11e7-86e6-987b612e52fe.png)

Also this brings me back to allowing custom CSS files to theme the Chrome ext. There is a lot you can do with CSS overrides. Personally I would like to see it included in the repo like ohmyzh 

https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

I think this gets more and more important as features get added. Join is no longer a notification/sms app or a pushbullet clone. It keeps growing.

**Comment by mrkevinlin** [comment]
You're right. I was just proposing a stopgap patch to avoid rocking the boat too much. 

There may need to be a sweeping clean up of the elements and CSS that will allow for easier adjustment of colors or even the themes like you suggested. Reduce redundancy, simplify divs and the like, make simpler and clearer class names, etc.

**Comment by joaomgcd** [comment]
Whatever you both think looks better is fine by me :D As you know, it looks fine for me either way.
