### ISSUE TITLE
Tighten up the device icons a bit

### ISSUE THREAD

**Issue by tommyent** [joaomgcd/JoinChrome#5]
Right now .device is set to 70px. With the current width of the window it allows for 5.85 icons. If we drop that a few pixels we can get in another device icon on the line. Before and after pics below.

Thoughts?

![screenshot 2016-06-08 14 11 14](https://cloud.githubusercontent.com/assets/509970/15905627/88fa82e8-2d83-11e6-860f-65c82bc7bfda.png)
![screenshot 2016-06-08 14 15 13](https://cloud.githubusercontent.com/assets/509970/15905626/88eb071e-2d83-11e6-9ff4-7b70442cb5b8.png)

**Comment by joaomgcd** [comment]
The problem is that sometimes people have long device names and they will look bad if icons are too close..

**Comment by joaomgcd** [comment]
Ok, having looked at it, you're right :) With 66px it does look better. I'll change it thanks
