### ISSUE TITLE
Highly requested dark theme

### ISSUE THREAD

**Issue by mrkevinlin** [joaomgcd/JoinChrome#50]
Hello, I have been testing implementing a dark theme on a separate branch.

http://imgur.com/a/nHP2k
Here's what it looks like so far. 

There's simply a toggle (http://imgur.com/a/DgbTo) in the options to trigger it.

The colors can be adjusted, I just used some Google-suggested blue-gray material palettes to fill in the colors just to see how it would look. Any suggestions are welcome.

**Comment by tommyent** [comment]
Pretty close to what I've used in the past. I never got around to finishing it though. 


![untitled-1](https://cloud.githubusercontent.com/assets/509970/24688099/cfedcdb4-198b-11e7-8d7f-d9eebb7a6643.jpg)

**Comment by joaomgcd** [comment]
Looks good to me :D
