### ISSUE TITLE
Fail to merge conversation of non-contact number formats

### ISSUE THREAD

**Issue by krokofant** [joaomgcd/JoinChrome#55]
Se the following image 
![example](https://cloud.githubusercontent.com/assets/5908498/25099543/0877047c-23ad-11e7-876d-ea8703039a86.png)

+46706 and 0706 are the same non-contact and the same number.
I first sent the text via Join and then got a response.
On the phone the conversation is merged.
On join it is separated.

**Comment by joaomgcd** [comment]
Sorry about that. Using the Join beta should fix that. https://play.google.com/apps/testing/com.joaomgcd.join

Please disable and re-enable the SMS service on your phone to refresh the conversation list. Thanks!

**Comment by krokofant** [comment]
I am on the 1.5.6b from 5 April. Did you just push out an update?

**Comment by joaomgcd** [comment]
I did not. Sorry, I thought you weren't on the beta. Can you please try disabling and re-enabling the SMS service on the phone? Thanks!
