### ISSUE TITLE
Cannot remove image to send via sms after attaching the image

### ISSUE THREAD

**Issue by kienD** [joaomgcd/JoinChrome#59]
Cannot remove image to send via sms after attaching the image in popout view.

The image attached will also persist when moving from one conversation to another, which may result in accidentally sending an image to someone that was meant for someone else.

**Comment by tommyent** [comment]
For the time being I found that closing the extension and reopening it removes the image but I do think it would be nice to have an option to remove the image.

**Comment by joaomgcd** [comment]
Ok, on the next release clicking the attachment icon again will clear the image. Hope this helps!

**Comment by kienD** [comment]
@joaomgcd I think clearing the image on navigating back to the sms overview screen would be a good idea as well.

This will prevent users from accidentally sending an image attached in one chat in another chat.

**Comment by joaomgcd** [comment]
Thanks, done for next release :)
