### ISSUE TITLE
Image Preview is hidden behind the attach and emoji button in popout view

### ISSUE THREAD

**Issue by kienD** [joaomgcd/JoinChrome#60]
The image preview is hidden behind the attachment and emoji buttons.

See Below:

![image_preview](https://cloud.githubusercontent.com/assets/16655146/26370722/8679a700-3fad-11e7-8b6d-0257d80e764d.jpg)

**Comment by joaomgcd** [comment]
@tommyent any suggestions on how to make this look better? :D Thanks in advance

**Comment by tommyent** [comment]
Simple 
![screen shot 2017-05-24 at 2 13 38 pm](https://cloud.githubusercontent.com/assets/509970/26419291/32418c62-408d-11e7-9965-2d8b5b902ee2.png)
A bit more
![screen shot 2017-05-24 at 2 21 21 pm](https://cloud.githubusercontent.com/assets/509970/26419322/4ee44e7c-408d-11e7-8be3-4f95946da1f3.jpg)

**Comment by kienD** [comment]
@tommyent,

I like the second one since it provides a better view of the image and gives the user an easy way to remove the image.

The second method also leaves the developer more room to iterate on, as it's easier to expand the amount of photos one can add to a chat before sending the image whereas the first method will run out of space quite quickly.

I think another possible improvement would be adding some sort of label that states that this is a preview as well.

Thanks guys!

**Comment by tommyent** [comment]
@kienD the red x I think would be enough to indicate that it's a preview. The second option is my favorite but the first one is just a matter of stripping out some css so it can be done in less than a minute. 

One other thing I was thinking about is I think I should have removed the chat bubble pointer.

**Comment by joaomgcd** [comment]
I have to say, I really don't like the second one just because I think people will be confused thinking that the message was already sent. 

Here's how it's going to look like in the next release:
![closemms](https://cloud.githubusercontent.com/assets/4864031/26447306/e3a725e0-413f-11e7-9d8c-84accbcb9bf6.png)

Hope this helps! :)
