### ISSUE TITLE
User cannot add emojis or attachments while the extension in NOT in popout view

### ISSUE THREAD

**Issue by kienD** [joaomgcd/JoinChrome#61]
User cannot add emojis or attachments while the extension in NOT in popout view.

**Comment by tommyent** [comment]
This is a Chrome thing. It's supposed to close when you click outside of it. Though I believe you can cheat this a bit in Windows with the drag and drop.

**Comment by kienD** [comment]
@tommyent,

Yeah, I somewhat figured this but I wanted to make an issue to be safe.

If that's the case, it's probably better to be consistent across the board.  I'll close this ticket.

Thanks!
