### ISSUE TITLE
No longer receiving shared things correctly (ERR_FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by SoullessWaffle** [joaomgcd/JoinChrome#62]
Instead of opening shared links or downloading shared photos, it opens a URL in Chrome like this whenever I share stuff from my Android:
```
chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/<base64(?) data>===:=<more base64(?) data>=
```
The page itself seems to be a 404 page.

![](https://puu.sh/w9rRA/1ed0a3a163.png)

This has been an issue since about a month or two ago (I use Join infrequently).

Join Chrome version 1.7.1
Chrome version 58.0.3029.110 (64-bit)
Windows 10

Join Android version 1.7.bf
Android 6.0.1
HTC 10

**Comment by joaomgcd** [comment]
Did you maybe enable encryption on your phone but not in chrome?

**Comment by SoullessWaffle** [comment]
That was it, thanks! I recently reinstalled Windows and must've forgotten to set the encryption key again.

Would it be possible to display some sort of error message on the page if the extension fails to read received data, in case other users come across an issue like this?

**Comment by joaomgcd** [comment]
Thank you! :) I'll try adding that somehow
