### ISSUE TITLE
Device section collapses

### ISSUE THREAD

**Issue by krokofant** [joaomgcd/JoinChrome#65]
macOS Sierra
Latest chrome stable
Join 1.7.7

![image](https://user-images.githubusercontent.com/5908498/27635687-57b2e068-5c08-11e7-8953-18efd28c60d2.png)

And if I refresh the device list:
![image](https://user-images.githubusercontent.com/5908498/27635700-6612637c-5c08-11e7-8226-cbfc2365e1ad.png)

I just connected another device to Join before this happened.

**Comment by joaomgcd** [comment]
Does this happen consistently, every time you refresh? Does the list appear again if you close and re-open the popup?

**Comment by krokofant** [comment]
It happened every time I refreshed and it maintained the collapsed state on next open. I could reset to the old view (without the newly added device) by disable and then re-enable the JoinChrome.

I was not able to reproduce this issue after restarting Chrome.

**Comment by joaomgcd** [comment]
Ok, I'll close this for now then. Let me know if it comes back, thanks!
