### ISSUE TITLE
Join's context menu option has ceased to work

### ISSUE THREAD

**Issue by wolflambert** [joaomgcd/JoinChrome#67]
I can't push links to my phone anymore by right-clicking on them. This was a vital feature of Join and I would like it back.

**Comment by joaomgcd** [comment]
Yes, I'm aware but unfortunately I can't fix it. Please check here: https://plus.google.com/+Jo%C3%A3oDias/posts/RkLexTvFiFL

Can you confirm that you are on the Chrome Beta?

**Comment by wolflambert** [comment]
I am. Oh, okay. Thanks!
