### ISSUE TITLE
Chrome icon color changing?

### ISSUE THREAD

**Issue by Vismund-Cygnus** [joaomgcd/JoinChrome#70]
I use a dark theme on Google Chrome and I can't see the icon on my taskbar. It completely blends in with the background. Example: https://i.imgur.com/txNTWzR.png

Any way we can have the option to use a dark or light icon?

**Comment by joaomgcd** [comment]
What if you disable the "Alternative popup icon" in the advanced settings?

**Comment by Vismund-Cygnus** [comment]
Crap. I didn't even realize I had even had that set. That fixed it, thank you.

**Comment by joaomgcd** [comment]
Great :)
