### ISSUE TITLE
'This device' is being sorted naturally by device name

### ISSUE THREAD

**Issue by braydenhouston** [joaomgcd/JoinChrome#71]
![image](https://user-images.githubusercontent.com/10109051/33325991-f6bc4fde-d410-11e7-8955-6164179b6bd0.png)

In this case 'This Device' was renamed from 'Chrome' to 'Chrome Work'. 

Following the rename the device was moved from being listed second to being listed where it would fall in a natural alphabetical order based on the new given name.

I believe the real issue here is that 'This Device' is being sorted naturally based on the actual name and not being forced to list first.

**Comment by joaomgcd** [comment]
Ok, thank you, fixed! :) Your own device will now always be the first on the list.
