### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by JoseExposito** [joaomgcd/JoinChrome#72]
Hi,

First at all, fantastic app, thanks a lot for your work.

I'd like to report an XSS vulnerability that could lead in security issues.
The use of innerHTML in notifications.js and many other files (grep -rnw . -e 'innerHTML') to display notifications/messages/etc is insecure.
Even tough innerHTML does not execute JavaScript, it does load iframes, so a malicious attacker could send you a WhatsApp message or similar with this structure:

`<iframe src="http://evil.com"></iframe>`

To remote execute code in your notification tab like for example to display an alert in my example:

![xss1](https://user-images.githubusercontent.com/1335948/34273468-bab817d4-e694-11e7-9c00-030acaff9425.png)

![xss2](https://user-images.githubusercontent.com/1335948/34273467-ba98b524-e694-11e7-8b03-5de739ac9669.png)

Consider use ![DOMPurify](https://github.com/cure53/DOMPurify) or similar to scape any kind of user input and avoid this problems.

**Comment by joaomgcd** [comment]
Thank you very much! :) Really appreciate the input! I've now fixed this! Let me know if you find any other issues, thanks again!
