### ISSUE TITLE
Swiping notifications on ChromeOS touchscreen causes psuedo 'Do not Disturb'

### ISSUE THREAD

**Issue by ForSquirel** [joaomgcd/JoinChrome#73]
If notifications are closed via mouse they will continue to work. If the touch screen is used to swipe or clear notifications then it causes all notifications (including system and other apps) to stay behind the window and not appear. Count will increase in the notification center and you can manually check the notifications but the no longer popup in front. I've been able to reproduce this many times. Problem persists even after Powerwash/extension reinstalls.

running Version 62.0.3202.97 (Official Build) (64-bit), Acer CB5-132T

mta: added OS/hardware

**Comment by joaomgcd** [comment]
Thanks for the report. Does this only happen for Join notifications and not for other app's notifications?

**Comment by ForSquirel** [comment]
It only happens if I swipe a join notification. If I swipe a join notification all notifications disappear until reboot. 

I can disable the join extension and have no issues with any notifications. But  as soon as I enable the extension the problem returns as soon as I swipe a join notification.

**Comment by joaomgcd** [comment]
I'm sorry but that sounds like a bug in Chrome OS. Unfortunately I don't have a Chrome OS device myself to test it but Join can't control what other notifications behave like. If they are not displaying then it must be an error with chrome OS/Chrome itself...

**Comment by ForSquirel** [comment]
Ok but what about the join notifications that get hidden? I don't get those
either.

**Comment by joaomgcd** [comment]
But you don't get any notification at all right? Or am I misunderstanding it?

**Comment by ForSquirel** [comment]
Something has changed and things are working correctly now. Originally the
issue was that if I swiped a Join notification it would cause all
notifications to not show. I would get the noise/alert but I would have to
go to the notification area to pull up the notification. Right now
everything is working as is so I guess the issue can be closed.

**Comment by joaomgcd** [comment]
Thank you for letting me know! :)
