### ISSUE TITLE
File push leaves extension unusable

### ISSUE THREAD

**Issue by Satori83** [joaomgcd/JoinChrome#77]
The file sent and downloaded perfectly. But afterwards I get this issue when opening the extension. I should also mention that I am using the Github commands version (unpacked extension)
I did uninstall and try it again with chrome store version, no problem

Error screenshot: [https://satori-design.d.pr/uLqPHB](url)

Mac OSX Sierra
Chrome Beta latest

**Comment by joaomgcd** [comment]
How are you sending the file exactly? Thanks

**Comment by Satori83** [comment]
I was in Photos on Pixel XL, chose share>Join>iMac . On iMac the notification pops up but when I go to use Join again the extension looks like that. If I use the one in Chrome Store, it works fine.

**Comment by joaomgcd** [comment]
Thank you. Can you please right-click the extension popup->inspect and check what the URL is at the top?
Also, do you have the option to automatically download the files disabled? Thanks

**Comment by Satori83** [comment]
https://pastebin.com/EZkV94pi

**Comment by joaomgcd** [comment]
Hi there. Thanks but I was just really looking for the URL at the top of the window :) Can you please check that? Thanks again!

**Comment by joaomgcd** [comment]
Great to hear! :D

**Comment by Satori83** [comment]
Since it was still not working on my new Macbook pro I tried to get the info you requested.  The only url I found at the top was: chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/devices.html
Heres a screenshot of where it came from: https://satori-design.d.pr/hLrh5l

Is that what you were asking for?

**Comment by joaomgcd** [comment]
Thank you. Does it work if you take that URL and open it in a new tab?

**Comment by Satori83** [comment]
No, when I take that url and open it ends up like this...
<img width="300" alt="join-app" src="https://user-images.githubusercontent.com/3317473/37445366-057ab91c-27ee-11e8-9afa-29d159029a9e.png">

**Comment by joaomgcd** [comment]
Ok, that's most likely soomething on your system that's blocking the file... That's weird.. Cause the file is most certainly there :/

**Comment by Satori83** [comment]
Something with chrome or OSX? Just curious...
