### ISSUE TITLE
Texts sent through chrome extension do not show up in Textra / SMS App

### ISSUE THREAD

**Issue by Chrisdf** [joaomgcd/JoinChrome#80]
When I send a message through the chrome extension, the messages correctly send but do not appear on Textra / Android Messenger at all, and disappear even from the chrome app after the extension is re-opened.

I am running Android 8.0 on Huawei P20

**Comment by joaomgcd** [comment]
That's a known issue. Please check here. Sorry!

https://joaoapps.com/join/faq/

**Comment by Chrisdf** [comment]
I have tried following the steps in the FAQ and they do not seem to be resolving my issue. This issue started happening after a SMS restore using the 'SMS Backup and Restore' app, and still occurs after swapping the default SMS app from Textra to Messages to Textra again. 

Do you believe this is still a related issue?
