### ISSUE TITLE
Not working in Brave (new chrome based browser)

### ISSUE THREAD

**Issue by jeroen7s** [joaomgcd/JoinChrome#84]
when installing the extension, it's not possible to login (login page doesn't appear)
also when checking the settings page none of the buttons/actions/tabs respond when clicking on them

**Comment by joaomgcd** [comment]
Sorry, Join was not meant to be used on browsers other than Chrome so I can't vouch for it working there...

**Comment by jeroen7s** [comment]
Too bad, it works fine in Vivaldi though, which is also a chrome based browser
Other extensions i use work fine in brave, seems like this is the only exception atm

**Comment by jeroen7s** [comment]
But i guess it's up to Brave devs to fix compatibility, will report it there

**Comment by tommyent** [comment]
I think only the beta/dev of Brave is currently Chromium. I've tested and it worked fine for me.

**Comment by jeroen7s** [comment]
@tommyent if you currently download the stabel version it's already chromium based, though the old muon based version won't automatically update to the chromium base atm as far as i'm aware
I'll test the beta later to see if it's just an issue in the current stable version

**Comment by jeroen7s** [comment]
Tested extension again on stable, seems to work
Not sure what caused it to break completely when i tried it before, but it seems to be fixed, so this ticket can stay closed :smiley:

**Comment by dogancelik** [comment]
Brave uses Chromium (Chrome) so I'd appreciate if you can try to fix this issue.

On diagnostics page, I get `alert()` at step 2 `Testing registration on Join's server...`:
```
Unknown error: TypeError: Cannot read property 'where' of null
```

![diag2](https://user-images.githubusercontent.com/486818/50532703-365d5c00-0b2e-11e9-91a7-df974d278917.png)

**Comment by jeroen7s** [comment]
getting similar error, but the sending push to server... also gives an error for me
however, pushing tabs to my phone seems to work fine

**Comment by tommyent** [comment]
@dogancelik @jeroen7s Brave removed both GCM and FCM (Oct/Nov) so currently it will no longer work with Brave.

**Comment by jeroen7s** [comment]
Just today started my browser and the test notifications which failed yesterday have arrived
in diagnostics the "Receiving Push from server..." no longer fails, only the "Receiving Push with GCM key..." still fails, but that's to be expected, the important part is that receiving pushes works now :+1:

**Comment by mickdekkers** [comment]
Good news: Join now works in Brave 🎉

You just need to enable the "Google Services for Push Messaging" setting in Brave for it to work. See https://github.com/brave/brave-browser/issues/2408#issuecomment-546843282

After you've done this, all the tests in the diagnostics tab will pass:

![A screenshot of Join's diagnostics tab, taken after running the tests in Brave. All the tests have passed.](https://user-images.githubusercontent.com/5085260/71467791-44d36780-27c4-11ea-9115-e2e5ccd40c63.png)

Tested on Brave `Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)`.

**Comment by joaomgcd** [comment]
Nice :D Thanks for letting us know!
