### ISSUE TITLE
Chrome/Windows 10 - integration with the notification system

### ISSUE THREAD

**Issue by jed84** [joaomgcd/JoinChrome#89]
I am not sure if this is a bug on my side or this is something which is not covered by the Chrome extension.

Explanation.
Currently, all notifications I am receiving via Join extension on Chrome are styled in the same way as default Chrome notifications. Chrome provides support for native Windows 10 notifications that are integrated with the taskbar.
I am on the latest Windows 10 and Chrome and on my side, this is not supported - all notifications look like this:
![ScreenClip](https://user-images.githubusercontent.com/47121522/60374513-c3f60780-99fc-11e9-9a22-c8c9fcd654b5.png)

My question is: is this some bug on my side or Join does not support native notifications yet?

**Comment by joaomgcd** [comment]
That is not controlled by extensions. It's a Chrome setting you can enable/disable. Check [here](https://pureinfotech.com/enable-native-chrome-notifications-windows-10/).

Hope this helps!
