### ISSUE TITLE
js/base/extensions.js breaks the included Material Design library

### ISSUE THREAD

**Issue by mrkevinlin** [joaomgcd/JoinChrome#9]
The console throws errors and some functionality is broken.

The errors first show up in this commit: 887d3d7f46cad80bce37885dd9a5625ed9b337f4
https://github.com/joaomgcd/JoinChrome/commit/887d3d7f46cad80bce37885dd9a5625ed9b337f4 because of the inclusion of the extensions.js file in devices.html. The removal of these specific lines fixes the error: 

> Object.prototype.applyProps = function(objToApply){
>     if(!objToApply){
>         return;
>     }
>     for(var prop in objToApply){
>     	var value = objToApply[prop];
> 		if(value && value.toClass() != "[object Function]"){
> 			this[prop] = value;
> 		}
>     }
>     return this;
> };
> Object.prototype.toClass = function(){
>   return {}.toString.call(this);
> };
> Object.prototype.isString = function(){
>   return this.toClass() == "[object String]";
> };
> Object.prototype.isArray = function(){
>   return this.toClass() == "[object Array]";
> };

Even though these lines and extensions.js have existed for several commits, the errors only occur once you import it into devices.html.

Changing the import order of your JS file and the materialize libraries in devices.html resolves one kind of error but introduces a new kind.

Sorry I'm not sure what the code does so I can't really suggest solutions, but I've gotten as much info as I can.

**Comment by joaomgcd** [comment]
Ok, fixed on latest commit. Thanks for figuring it out! :+1:
