### ISSUE TITLE
Sign-in not working on the new Edge Chromium browser

### ISSUE THREAD

**Issue by gh-nobi** [joaomgcd/JoinChrome#93]
It is possible to install the Chrome extension on the new Chromium Edge browser. I then manage to log in, but no device shows up. And when I try the "test" button, I get this error: Testing registration on Join's server... "noauth", together with a popup: Unknown error: TypeError: Cannot read property 'where' of null.

**Comment by joaomgcd** [comment]
Edge is missing a required API so Join won't work on it, sorry!

**Comment by gh-nobi** [comment]
Looks like I won't use edge then! :-)
