### ISSUE TITLE
Diagnostics stuck on "Testing registration on Join's server"

### ISSUE THREAD

**Issue by lbux** [joaomgcd/JoinChrome#95]
Every day or so I have to manually restart my browser to get Join to function properly. As far as I can tell most features work until I try to send a file from my PC to my phone. Once I try to do that nothing is sent and the window for the join extension is constantly "loading" ([as seen here](https://gfycat.com/FlashyLikableCod))

I am using Brave instead of Chrome so perhaps there might be an issue there?

**Comment by joaomgcd** [comment]
Did you try sending a file by drag-dropping it onto the window? Does that make it not block?

**Comment by lbux** [comment]
Yes, that is the method I tried and it usually never works until I restart.

**Comment by joaomgcd** [comment]
Can you please try this:
- go into Chrome
- settings
- extensions
- enable developer mode
- click on join.html
- go to the console tab
- send a file like you usually do and block the extension
- see if anything appears in the console tab

**Comment by lbux** [comment]
My browser extension seems to have updated recently as I now see the LAN icon between my devices, and I am unable to replicate the issue. If this issue persists I will reopen this thread with the details requested.

**Comment by lbux** [comment]
Okay, the issue is still persisting. It seems to be experiencing an issue during the authentication process and it just says (canceled). I would expand the Name column, but it has my token and clientID.
![zkd5Ldq](https://user-images.githubusercontent.com/30765968/82530057-3f6b1680-9af1-11ea-85f9-7300addfecf3.png)

The first 4 lines are the responses I get when I first open the extension and the remaining 3 are the ones I get when trying to send a file.

**Comment by lbux** [comment]
@joaomgcd I am still experiencing this issue :)

**Comment by joaomgcd** [comment]
Sorry, I don't officially support the brave browser, just Chrome :(

**Comment by lbux** [comment]
I see. That is unfortunate. Thank you!
