### ISSUE TITLE
[Feature Request] Add an option to not open Google Account Sign-In tabs when you log out of Google

### ISSUE THREAD

**Issue by serovar** [joaomgcd/JoinChrome#96]
Since most of the features of Join works fine without staying logged in to Google (pushes and clipboard sync work without it, and even file transfers on the same network), I think that an option to not open Google Account Sign-In tabs when you log out of Google would be a great quality of life improvement for people who don't rely on Drive-related features and don't want to stay logged in to Google all the time (and don't want to be bugged by auto-opening tabs that they don't need).

**Comment by joaomgcd** [comment]
Hmm, so your suggestion is, log in once to register your device but then log out and don't ask to log in again?

**Comment by serovar** [comment]
I would prefer it in this way, to be honest, be I understand that some users would not like to be logged out of Google after logging in with the extension to register the device. What I am asking is simply to not being asked to log in again (automatically opening the Sign-In tab every once in a while) if the user logs out of Google, because it's an unnecessary nuisance.

**Comment by joaomgcd** [comment]
Thanks. Can you add that request here so I can give it proper priority? https://joaoapps.helprace.com/ Thanks!

**Comment by serovar** [comment]
[It seems that it already exists.](https://joaoapps.helprace.com/i195-option-to-disable-opening-new-tab-to-login-with-google-account-for-join-chrome-extension)

**Comment by joaomgcd** [comment]
Oh yeah, forgot about that :) Please vote for it then.

**Comment by serovar** [comment]
Done

**Comment by joaomgcd** [comment]
Thank you! :)
