### ISSUE TITLE
Join returning deep link instead of image when downloading from browser

### ISSUE THREAD

**Issue by lbux** [joaomgcd/JoinChrome#97]
Confirmed to be an issue on Chrome (although I daily drive Brave). Here's a [video](https://www.youtube.com/watch?v=Y6ztRwV6NCU&feature=youtu.be) showcasing the exact error

**Comment by lbux** [comment]
I would like to note that a file does indeed get downloaded but not an *image* file. Converting the file name extension to a jpg ends up making the file work.

**Comment by joaomgcd** [comment]
Hhmm, the idea is to open the file in a local image viewer like Google Photos, not a browser. Can you please try that? If you want to view the image directly just use the "Open" option instead :)

**Comment by lbux** [comment]
Yes, that does work. However, the issue seems to be that the image isn't being downloaded with the proper extension. If you take a look at my Join files all the videos are downloaded with the .mp4/webm file extension and the system knows to open them with my default video player. Now, if you look at the image files (the ones missing any file extension) the system does not know what to do with them and I have to manually add the extension to open the file.

![Screenshot_20200605-111905](https://user-images.githubusercontent.com/30765968/83910164-ea4d1880-a71e-11ea-89b1-f518b2d55f2b.png)

**Comment by joaomgcd** [comment]
Oh I see. So I take it this only happens if the website in question doesn't have a file name for their images?

**Comment by lbux** [comment]
Interesting. That does seem to be the case. I tried downloading an image from Reddit and it worked fine; however, Twitter images do not work. This is odd because I've downloaded images off Twitter in the past and they've downloaded fine.

**Comment by joaomgcd** [comment]
Maybe Twitter changed something recently... I've now changed the Android app in a way that should make this hopefully work :)

Can you please try this version? https://drive.google.com/file/d/18V276YwSlfc3voV1s-SUxdCfoP9fCerp/view?usp=sharing

**Comment by lbux** [comment]
Yes that works now! The .jpg extension is now present and the Android system knows to open it with the default photo viewer.

**Comment by joaomgcd** [comment]
Great :)

**Comment by lbux** [comment]
I would like to add that with the apk you provided every time Join is opened it displays a notification about not being able to use port 1. It then assigns a random port (as designed) but still nags you with the notification. In order to get rid of the constant notification, I had to set it to a specific port in the Advanced Settings. Not really a big issue but something you might be aware of.

**Comment by joaomgcd** [comment]
Thank you for mentioning it! :)
