### ISSUE TITLE
Chrome Extension in Vivaldi browser shows only a small square when clicked.

### ISSUE THREAD

**Issue by SimoFiuz** [joaomgcd/JoinChrome#98]
Join extension v. 1.8.22
Vivaldi v. 3.0.1874.38

Extension installed from Chrome store. When clicked in the extension bar, it shows just a tiny square where I guess the whole content of its panel really is.

Gif of the behavior: https://i.imgur.com/huyVZX1.gifv

**Comment by joaomgcd** [comment]
Hi. Sorry Vivaldi is not supported. Just Chrome for now.
