### ISSUE TITLE
Suggestion: Perform a media scan after file transfer

### ISSUE THREAD

**Issue by lbux** [joaomgcd/JoinChrome#99]
One of my biggest issues with Join is that with every file transfer (photo/video) that I want to upload to Twitter, Instagram, etc I have to restart my phone for the media scanner to be triggered and the apps to register the file as present in their respective media browsers.

For instance, I use youtube-dl through a terminal on my phone to download videos and after each install, a script runs to run a media scan. I was wondering if that is something that can be done on Join as well.

I believe [this ](https://developer.android.com/reference/android/media/MediaScannerConnection)is the documentation on the specific service.

**Comment by joaomgcd** [comment]
Can you add that request here so I can give it proper priority? https://joaoapps.helprace.com/ Thanks!

**Comment by lbux** [comment]
Great! I will add it there.
